/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/image-generation/wrangler.jsonc --include-runtime=false --env-interface=ImageGenerationConsumerEnv workers/image-generation/worker-configuration.d.ts` (hash: ab594ad47a0caaf7962192cdfacccd18)
interface __BaseEnv_ImageGenerationConsumerEnv {
	DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_ImageGenerationConsumerEnv {}
}
interface ImageGenerationConsumerEnv extends __BaseEnv_ImageGenerationConsumerEnv {}
