/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/image-generation/wrangler.jsonc --include-runtime=false --strict-vars=false --env-interface=ImageGenerationConsumerEnv workers/image-generation/worker-configuration.d.ts` (hash: 66a5748de4ba47a457f94cd792e38834)
interface __BaseEnv_ImageGenerationConsumerEnv {
	IMAGE_GENERATION_BUCKET: R2Bucket;
	DB: D1Database;
	IMAGE_GENERATION_ENABLED: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_ImageGenerationConsumerEnv {}
}
interface ImageGenerationConsumerEnv extends __BaseEnv_ImageGenerationConsumerEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "IMAGE_GENERATION_ENABLED">> {}
}
