/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as EventsRouteImport } from './routes/events'
import { Route as MatchesRouteImport } from './routes/matches'
import { Route as WarbandsRouteImport } from './routes/warbands'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsEventIdRouteImport } from './routes/events.$eventId'
import { Route as EventsNewRouteImport } from './routes/events.new'
import { Route as MatchesIndexRouteImport } from './routes/matches.index'
import { Route as MatchesMatchIdRouteImport } from './routes/matches.$matchId'
import { Route as MatchesNewRouteImport } from './routes/matches.new'
import { Route as WarbandsIndexRouteImport } from './routes/warbands.index'
import { Route as WarbandsWarbandIdRouteImport } from './routes/warbands.$warbandId'
import { Route as WarbandsNewRouteImport } from './routes/warbands.new'
import { Route as EventsEventIdIndexRouteImport } from './routes/events.$eventId.index'
import { Route as EventsEventIdDeleteRouteImport } from './routes/events.$eventId.delete'
import { Route as MatchesMatchIdIndexRouteImport } from './routes/matches.$matchId.index'
import { Route as MatchesMatchIdDeleteRouteImport } from './routes/matches.$matchId.delete'
import { Route as WarbandsWarbandIdIndexRouteImport } from './routes/warbands.$warbandId.index'
import { Route as WarbandsWarbandIdDeleteRouteImport } from './routes/warbands.$warbandId.delete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRoute = MatchesRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const WarbandsRoute = WarbandsRouteImport.update({
  id: '/warbands',
  path: '/warbands',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const EventsEventIdRoute = EventsEventIdRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRoute,
} as any)
const EventsNewRoute = EventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => EventsRoute,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatchesRoute,
} as any)
const MatchesMatchIdRoute = MatchesMatchIdRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => MatchesRoute,
} as any)
const MatchesNewRoute = MatchesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MatchesRoute,
} as any)
const WarbandsIndexRoute = WarbandsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WarbandsRoute,
} as any)
const WarbandsWarbandIdRoute = WarbandsWarbandIdRouteImport.update({
  id: '/$warbandId',
  path: '/$warbandId',
  getParentRoute: () => WarbandsRoute,
} as any)
const WarbandsNewRoute = WarbandsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WarbandsRoute,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const EventsEventIdDeleteRoute = EventsEventIdDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => EventsEventIdRoute,
} as any)
const MatchesMatchIdIndexRoute = MatchesMatchIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatchesMatchIdRoute,
} as any)
const MatchesMatchIdDeleteRoute = MatchesMatchIdDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => MatchesMatchIdRoute,
} as any)
const WarbandsWarbandIdIndexRoute = WarbandsWarbandIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WarbandsWarbandIdRoute,
} as any)
const WarbandsWarbandIdDeleteRoute = WarbandsWarbandIdDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => WarbandsWarbandIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/events': typeof EventsRouteWithChildren
  '/matches': typeof MatchesRouteWithChildren
  '/warbands': typeof WarbandsRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/events/new': typeof EventsNewRoute
  '/matches/$matchId': typeof MatchesMatchIdRouteWithChildren
  '/matches/new': typeof MatchesNewRoute
  '/warbands/$warbandId': typeof WarbandsWarbandIdRouteWithChildren
  '/warbands/new': typeof WarbandsNewRoute
  '/events/': typeof EventsIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/warbands/': typeof WarbandsIndexRoute
  '/events/$eventId/delete': typeof EventsEventIdDeleteRoute
  '/matches/$matchId/delete': typeof MatchesMatchIdDeleteRoute
  '/warbands/$warbandId/delete': typeof WarbandsWarbandIdDeleteRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/matches/$matchId/': typeof MatchesMatchIdIndexRoute
  '/warbands/$warbandId/': typeof WarbandsWarbandIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/events/new': typeof EventsNewRoute
  '/matches/new': typeof MatchesNewRoute
  '/warbands/new': typeof WarbandsNewRoute
  '/events': typeof EventsIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/warbands': typeof WarbandsIndexRoute
  '/events/$eventId/delete': typeof EventsEventIdDeleteRoute
  '/matches/$matchId/delete': typeof MatchesMatchIdDeleteRoute
  '/warbands/$warbandId/delete': typeof WarbandsWarbandIdDeleteRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
  '/matches/$matchId': typeof MatchesMatchIdIndexRoute
  '/warbands/$warbandId': typeof WarbandsWarbandIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/events': typeof EventsRouteWithChildren
  '/matches': typeof MatchesRouteWithChildren
  '/warbands': typeof WarbandsRouteWithChildren
  '/events/$eventId': typeof EventsEventIdRouteWithChildren
  '/events/new': typeof EventsNewRoute
  '/matches/$matchId': typeof MatchesMatchIdRouteWithChildren
  '/matches/new': typeof MatchesNewRoute
  '/warbands/$warbandId': typeof WarbandsWarbandIdRouteWithChildren
  '/warbands/new': typeof WarbandsNewRoute
  '/events/': typeof EventsIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/warbands/': typeof WarbandsIndexRoute
  '/events/$eventId/delete': typeof EventsEventIdDeleteRoute
  '/matches/$matchId/delete': typeof MatchesMatchIdDeleteRoute
  '/warbands/$warbandId/delete': typeof WarbandsWarbandIdDeleteRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/matches/$matchId/': typeof MatchesMatchIdIndexRoute
  '/warbands/$warbandId/': typeof WarbandsWarbandIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo'
    | '/events'
    | '/matches'
    | '/warbands'
    | '/events/$eventId'
    | '/events/new'
    | '/matches/$matchId'
    | '/matches/new'
    | '/warbands/$warbandId'
    | '/warbands/new'
    | '/events/'
    | '/matches/'
    | '/warbands/'
    | '/events/$eventId/delete'
    | '/matches/$matchId/delete'
    | '/warbands/$warbandId/delete'
    | '/events/$eventId/'
    | '/matches/$matchId/'
    | '/warbands/$warbandId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/events/new'
    | '/matches/new'
    | '/warbands/new'
    | '/events'
    | '/matches'
    | '/warbands'
    | '/events/$eventId/delete'
    | '/matches/$matchId/delete'
    | '/warbands/$warbandId/delete'
    | '/events/$eventId'
    | '/matches/$matchId'
    | '/warbands/$warbandId'
  id:
    | '__root__'
    | '/'
    | '/demo'
    | '/events'
    | '/matches'
    | '/warbands'
    | '/events/$eventId'
    | '/events/new'
    | '/matches/$matchId'
    | '/matches/new'
    | '/warbands/$warbandId'
    | '/warbands/new'
    | '/events/'
    | '/matches/'
    | '/warbands/'
    | '/events/$eventId/delete'
    | '/matches/$matchId/delete'
    | '/warbands/$warbandId/delete'
    | '/events/$eventId/'
    | '/matches/$matchId/'
    | '/warbands/$warbandId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoRoute: typeof DemoRoute
  EventsRoute: typeof EventsRouteWithChildren
  MatchesRoute: typeof MatchesRouteWithChildren
  WarbandsRoute: typeof WarbandsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warbands': {
      id: '/warbands'
      path: '/warbands'
      fullPath: '/warbands'
      preLoaderRoute: typeof WarbandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/new': {
      id: '/events/new'
      path: '/new'
      fullPath: '/events/new'
      preLoaderRoute: typeof EventsNewRouteImport
      parentRoute: typeof EventsRoute
    }
    '/matches/': {
      id: '/matches/'
      path: '/'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/matches/new': {
      id: '/matches/new'
      path: '/new'
      fullPath: '/matches/new'
      preLoaderRoute: typeof MatchesNewRouteImport
      parentRoute: typeof MatchesRoute
    }
    '/warbands/': {
      id: '/warbands/'
      path: '/'
      fullPath: '/warbands/'
      preLoaderRoute: typeof WarbandsIndexRouteImport
      parentRoute: typeof WarbandsRoute
    }
    '/warbands/$warbandId': {
      id: '/warbands/$warbandId'
      path: '/$warbandId'
      fullPath: '/warbands/$warbandId'
      preLoaderRoute: typeof WarbandsWarbandIdRouteImport
      parentRoute: typeof WarbandsRoute
    }
    '/warbands/new': {
      id: '/warbands/new'
      path: '/new'
      fullPath: '/warbands/new'
      preLoaderRoute: typeof WarbandsNewRouteImport
      parentRoute: typeof WarbandsRoute
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/events/$eventId/delete': {
      id: '/events/$eventId/delete'
      path: '/delete'
      fullPath: '/events/$eventId/delete'
      preLoaderRoute: typeof EventsEventIdDeleteRouteImport
      parentRoute: typeof EventsEventIdRoute
    }
    '/matches/$matchId/': {
      id: '/matches/$matchId/'
      path: '/'
      fullPath: '/matches/$matchId/'
      preLoaderRoute: typeof MatchesMatchIdIndexRouteImport
      parentRoute: typeof MatchesMatchIdRoute
    }
    '/matches/$matchId/delete': {
      id: '/matches/$matchId/delete'
      path: '/delete'
      fullPath: '/matches/$matchId/delete'
      preLoaderRoute: typeof MatchesMatchIdDeleteRouteImport
      parentRoute: typeof MatchesMatchIdRoute
    }
    '/warbands/$warbandId/': {
      id: '/warbands/$warbandId/'
      path: '/'
      fullPath: '/warbands/$warbandId/'
      preLoaderRoute: typeof WarbandsWarbandIdIndexRouteImport
      parentRoute: typeof WarbandsWarbandIdRoute
    }
    '/warbands/$warbandId/delete': {
      id: '/warbands/$warbandId/delete'
      path: '/delete'
      fullPath: '/warbands/$warbandId/delete'
      preLoaderRoute: typeof WarbandsWarbandIdDeleteRouteImport
      parentRoute: typeof WarbandsWarbandIdRoute
    }
  }
}

interface EventsEventIdRouteChildren {
  EventsEventIdDeleteRoute: typeof EventsEventIdDeleteRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
}

const EventsEventIdRouteChildren: EventsEventIdRouteChildren = {
  EventsEventIdDeleteRoute: EventsEventIdDeleteRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
}

const EventsEventIdRouteWithChildren = EventsEventIdRoute._addFileChildren(
  EventsEventIdRouteChildren,
)

interface EventsRouteChildren {
  EventsEventIdRoute: typeof EventsEventIdRouteWithChildren
  EventsNewRoute: typeof EventsNewRoute
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsEventIdRoute: EventsEventIdRouteWithChildren,
  EventsNewRoute: EventsNewRoute,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface MatchesMatchIdRouteChildren {
  MatchesMatchIdDeleteRoute: typeof MatchesMatchIdDeleteRoute
  MatchesMatchIdIndexRoute: typeof MatchesMatchIdIndexRoute
}

const MatchesMatchIdRouteChildren: MatchesMatchIdRouteChildren = {
  MatchesMatchIdDeleteRoute: MatchesMatchIdDeleteRoute,
  MatchesMatchIdIndexRoute: MatchesMatchIdIndexRoute,
}

const MatchesMatchIdRouteWithChildren = MatchesMatchIdRoute._addFileChildren(
  MatchesMatchIdRouteChildren,
)

interface MatchesRouteChildren {
  MatchesMatchIdRoute: typeof MatchesMatchIdRouteWithChildren
  MatchesNewRoute: typeof MatchesNewRoute
  MatchesIndexRoute: typeof MatchesIndexRoute
}

const MatchesRouteChildren: MatchesRouteChildren = {
  MatchesMatchIdRoute: MatchesMatchIdRouteWithChildren,
  MatchesNewRoute: MatchesNewRoute,
  MatchesIndexRoute: MatchesIndexRoute,
}

const MatchesRouteWithChildren =
  MatchesRoute._addFileChildren(MatchesRouteChildren)

interface WarbandsWarbandIdRouteChildren {
  WarbandsWarbandIdDeleteRoute: typeof WarbandsWarbandIdDeleteRoute
  WarbandsWarbandIdIndexRoute: typeof WarbandsWarbandIdIndexRoute
}

const WarbandsWarbandIdRouteChildren: WarbandsWarbandIdRouteChildren = {
  WarbandsWarbandIdDeleteRoute: WarbandsWarbandIdDeleteRoute,
  WarbandsWarbandIdIndexRoute: WarbandsWarbandIdIndexRoute,
}

const WarbandsWarbandIdRouteWithChildren =
  WarbandsWarbandIdRoute._addFileChildren(WarbandsWarbandIdRouteChildren)

interface WarbandsRouteChildren {
  WarbandsWarbandIdRoute: typeof WarbandsWarbandIdRouteWithChildren
  WarbandsNewRoute: typeof WarbandsNewRoute
  WarbandsIndexRoute: typeof WarbandsIndexRoute
}

const WarbandsRouteChildren: WarbandsRouteChildren = {
  WarbandsWarbandIdRoute: WarbandsWarbandIdRouteWithChildren,
  WarbandsNewRoute: WarbandsNewRoute,
  WarbandsIndexRoute: WarbandsIndexRoute,
}

const WarbandsRouteWithChildren = WarbandsRoute._addFileChildren(
  WarbandsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoRoute: DemoRoute,
  EventsRoute: EventsRouteWithChildren,
  MatchesRoute: MatchesRouteWithChildren,
  WarbandsRoute: WarbandsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
