/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as EventsRouteRouteImport } from './routes/events/route'
import { Route as MatchesRouteRouteImport } from './routes/matches/route'
import { Route as WarbandsRouteRouteImport } from './routes/warbands/route'
import { Route as WarriorsRouteRouteImport } from './routes/warriors/route'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsEventIdRouteRouteImport } from './routes/events/$eventId/route'
import { Route as MatchesIndexRouteImport } from './routes/matches/index'
import { Route as MatchesMatchIdRouteRouteImport } from './routes/matches/$matchId/route'
import { Route as WarbandsIndexRouteImport } from './routes/warbands/index'
import { Route as WarbandsWarbandIdRouteRouteImport } from './routes/warbands/$warbandId/route'
import { Route as WarriorsIndexRouteImport } from './routes/warriors/index'
import { Route as WarriorsWarriorIdRouteRouteImport } from './routes/warriors/$warriorId/route'
import { Route as EventsEventIdIndexRouteImport } from './routes/events/$eventId/index'
import { Route as EventsEventIdDeleteRouteImport } from './routes/events/$eventId/delete'
import { Route as MatchesMatchIdIndexRouteImport } from './routes/matches/$matchId/index'
import { Route as MatchesMatchIdDeleteRouteImport } from './routes/matches/$matchId/delete'
import { Route as WarbandsWarbandIdIndexRouteImport } from './routes/warbands/$warbandId/index'
import { Route as WarbandsWarbandIdDeleteRouteImport } from './routes/warbands/$warbandId/delete'
import { Route as WarriorsWarriorIdIndexRouteImport } from './routes/warriors/$warriorId/index'
import { Route as WarriorsWarriorIdDeleteRouteImport } from './routes/warriors/$warriorId/delete'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRouteRoute = EventsRouteRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchesRouteRoute = MatchesRouteRouteImport.update({
  id: '/matches',
  path: '/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const WarbandsRouteRoute = WarbandsRouteRouteImport.update({
  id: '/warbands',
  path: '/warbands',
  getParentRoute: () => rootRouteImport,
} as any)
const WarriorsRouteRoute = WarriorsRouteRouteImport.update({
  id: '/warriors',
  path: '/warriors',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRouteRoute,
} as any)
const EventsEventIdRouteRoute = EventsEventIdRouteRouteImport.update({
  id: '/$eventId',
  path: '/$eventId',
  getParentRoute: () => EventsRouteRoute,
} as any)
const MatchesIndexRoute = MatchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatchesRouteRoute,
} as any)
const MatchesMatchIdRouteRoute = MatchesMatchIdRouteRouteImport.update({
  id: '/$matchId',
  path: '/$matchId',
  getParentRoute: () => MatchesRouteRoute,
} as any)
const WarbandsIndexRoute = WarbandsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WarbandsRouteRoute,
} as any)
const WarbandsWarbandIdRouteRoute = WarbandsWarbandIdRouteRouteImport.update({
  id: '/$warbandId',
  path: '/$warbandId',
  getParentRoute: () => WarbandsRouteRoute,
} as any)
const WarriorsIndexRoute = WarriorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WarriorsRouteRoute,
} as any)
const WarriorsWarriorIdRouteRoute = WarriorsWarriorIdRouteRouteImport.update({
  id: '/$warriorId',
  path: '/$warriorId',
  getParentRoute: () => WarriorsRouteRoute,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsEventIdRouteRoute,
} as any)
const EventsEventIdDeleteRoute = EventsEventIdDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => EventsEventIdRouteRoute,
} as any)
const MatchesMatchIdIndexRoute = MatchesMatchIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MatchesMatchIdRouteRoute,
} as any)
const MatchesMatchIdDeleteRoute = MatchesMatchIdDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => MatchesMatchIdRouteRoute,
} as any)
const WarbandsWarbandIdIndexRoute = WarbandsWarbandIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WarbandsWarbandIdRouteRoute,
} as any)
const WarbandsWarbandIdDeleteRoute = WarbandsWarbandIdDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => WarbandsWarbandIdRouteRoute,
} as any)
const WarriorsWarriorIdIndexRoute = WarriorsWarriorIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WarriorsWarriorIdRouteRoute,
} as any)
const WarriorsWarriorIdDeleteRoute = WarriorsWarriorIdDeleteRouteImport.update({
  id: '/delete',
  path: '/delete',
  getParentRoute: () => WarriorsWarriorIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRouteRouteWithChildren
  '/matches': typeof MatchesRouteRouteWithChildren
  '/warbands': typeof WarbandsRouteRouteWithChildren
  '/warriors': typeof WarriorsRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/events/$eventId': typeof EventsEventIdRouteRouteWithChildren
  '/matches/$matchId': typeof MatchesMatchIdRouteRouteWithChildren
  '/warbands/$warbandId': typeof WarbandsWarbandIdRouteRouteWithChildren
  '/warriors/$warriorId': typeof WarriorsWarriorIdRouteRouteWithChildren
  '/events/': typeof EventsIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/warbands/': typeof WarbandsIndexRoute
  '/warriors/': typeof WarriorsIndexRoute
  '/events/$eventId/delete': typeof EventsEventIdDeleteRoute
  '/matches/$matchId/delete': typeof MatchesMatchIdDeleteRoute
  '/warbands/$warbandId/delete': typeof WarbandsWarbandIdDeleteRoute
  '/warriors/$warriorId/delete': typeof WarriorsWarriorIdDeleteRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/matches/$matchId/': typeof MatchesMatchIdIndexRoute
  '/warbands/$warbandId/': typeof WarbandsWarbandIdIndexRoute
  '/warriors/$warriorId/': typeof WarriorsWarriorIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/events': typeof EventsIndexRoute
  '/matches': typeof MatchesIndexRoute
  '/warbands': typeof WarbandsIndexRoute
  '/warriors': typeof WarriorsIndexRoute
  '/events/$eventId/delete': typeof EventsEventIdDeleteRoute
  '/matches/$matchId/delete': typeof MatchesMatchIdDeleteRoute
  '/warbands/$warbandId/delete': typeof WarbandsWarbandIdDeleteRoute
  '/warriors/$warriorId/delete': typeof WarriorsWarriorIdDeleteRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
  '/matches/$matchId': typeof MatchesMatchIdIndexRoute
  '/warbands/$warbandId': typeof WarbandsWarbandIdIndexRoute
  '/warriors/$warriorId': typeof WarriorsWarriorIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRouteRouteWithChildren
  '/matches': typeof MatchesRouteRouteWithChildren
  '/warbands': typeof WarbandsRouteRouteWithChildren
  '/warriors': typeof WarriorsRouteRouteWithChildren
  '/demo': typeof DemoRoute
  '/events/$eventId': typeof EventsEventIdRouteRouteWithChildren
  '/matches/$matchId': typeof MatchesMatchIdRouteRouteWithChildren
  '/warbands/$warbandId': typeof WarbandsWarbandIdRouteRouteWithChildren
  '/warriors/$warriorId': typeof WarriorsWarriorIdRouteRouteWithChildren
  '/events/': typeof EventsIndexRoute
  '/matches/': typeof MatchesIndexRoute
  '/warbands/': typeof WarbandsIndexRoute
  '/warriors/': typeof WarriorsIndexRoute
  '/events/$eventId/delete': typeof EventsEventIdDeleteRoute
  '/matches/$matchId/delete': typeof MatchesMatchIdDeleteRoute
  '/warbands/$warbandId/delete': typeof WarbandsWarbandIdDeleteRoute
  '/warriors/$warriorId/delete': typeof WarriorsWarriorIdDeleteRoute
  '/events/$eventId/': typeof EventsEventIdIndexRoute
  '/matches/$matchId/': typeof MatchesMatchIdIndexRoute
  '/warbands/$warbandId/': typeof WarbandsWarbandIdIndexRoute
  '/warriors/$warriorId/': typeof WarriorsWarriorIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/matches'
    | '/warbands'
    | '/warriors'
    | '/demo'
    | '/events/$eventId'
    | '/matches/$matchId'
    | '/warbands/$warbandId'
    | '/warriors/$warriorId'
    | '/events/'
    | '/matches/'
    | '/warbands/'
    | '/warriors/'
    | '/events/$eventId/delete'
    | '/matches/$matchId/delete'
    | '/warbands/$warbandId/delete'
    | '/warriors/$warriorId/delete'
    | '/events/$eventId/'
    | '/matches/$matchId/'
    | '/warbands/$warbandId/'
    | '/warriors/$warriorId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/events'
    | '/matches'
    | '/warbands'
    | '/warriors'
    | '/events/$eventId/delete'
    | '/matches/$matchId/delete'
    | '/warbands/$warbandId/delete'
    | '/warriors/$warriorId/delete'
    | '/events/$eventId'
    | '/matches/$matchId'
    | '/warbands/$warbandId'
    | '/warriors/$warriorId'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/matches'
    | '/warbands'
    | '/warriors'
    | '/demo'
    | '/events/$eventId'
    | '/matches/$matchId'
    | '/warbands/$warbandId'
    | '/warriors/$warriorId'
    | '/events/'
    | '/matches/'
    | '/warbands/'
    | '/warriors/'
    | '/events/$eventId/delete'
    | '/matches/$matchId/delete'
    | '/warbands/$warbandId/delete'
    | '/warriors/$warriorId/delete'
    | '/events/$eventId/'
    | '/matches/$matchId/'
    | '/warbands/$warbandId/'
    | '/warriors/$warriorId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRouteRoute: typeof EventsRouteRouteWithChildren
  MatchesRouteRoute: typeof MatchesRouteRouteWithChildren
  WarbandsRouteRoute: typeof WarbandsRouteRouteWithChildren
  WarriorsRouteRoute: typeof WarriorsRouteRouteWithChildren
  DemoRoute: typeof DemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matches': {
      id: '/matches'
      path: '/matches'
      fullPath: '/matches'
      preLoaderRoute: typeof MatchesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warbands': {
      id: '/warbands'
      path: '/warbands'
      fullPath: '/warbands'
      preLoaderRoute: typeof WarbandsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warriors': {
      id: '/warriors'
      path: '/warriors'
      fullPath: '/warriors'
      preLoaderRoute: typeof WarriorsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRouteRoute
    }
    '/events/$eventId': {
      id: '/events/$eventId'
      path: '/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdRouteRouteImport
      parentRoute: typeof EventsRouteRoute
    }
    '/matches/': {
      id: '/matches/'
      path: '/'
      fullPath: '/matches/'
      preLoaderRoute: typeof MatchesIndexRouteImport
      parentRoute: typeof MatchesRouteRoute
    }
    '/matches/$matchId': {
      id: '/matches/$matchId'
      path: '/$matchId'
      fullPath: '/matches/$matchId'
      preLoaderRoute: typeof MatchesMatchIdRouteRouteImport
      parentRoute: typeof MatchesRouteRoute
    }
    '/warbands/': {
      id: '/warbands/'
      path: '/'
      fullPath: '/warbands/'
      preLoaderRoute: typeof WarbandsIndexRouteImport
      parentRoute: typeof WarbandsRouteRoute
    }
    '/warbands/$warbandId': {
      id: '/warbands/$warbandId'
      path: '/$warbandId'
      fullPath: '/warbands/$warbandId'
      preLoaderRoute: typeof WarbandsWarbandIdRouteRouteImport
      parentRoute: typeof WarbandsRouteRoute
    }
    '/warriors/': {
      id: '/warriors/'
      path: '/'
      fullPath: '/warriors/'
      preLoaderRoute: typeof WarriorsIndexRouteImport
      parentRoute: typeof WarriorsRouteRoute
    }
    '/warriors/$warriorId': {
      id: '/warriors/$warriorId'
      path: '/$warriorId'
      fullPath: '/warriors/$warriorId'
      preLoaderRoute: typeof WarriorsWarriorIdRouteRouteImport
      parentRoute: typeof WarriorsRouteRoute
    }
    '/events/$eventId/': {
      id: '/events/$eventId/'
      path: '/'
      fullPath: '/events/$eventId/'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof EventsEventIdRouteRoute
    }
    '/events/$eventId/delete': {
      id: '/events/$eventId/delete'
      path: '/delete'
      fullPath: '/events/$eventId/delete'
      preLoaderRoute: typeof EventsEventIdDeleteRouteImport
      parentRoute: typeof EventsEventIdRouteRoute
    }
    '/matches/$matchId/': {
      id: '/matches/$matchId/'
      path: '/'
      fullPath: '/matches/$matchId/'
      preLoaderRoute: typeof MatchesMatchIdIndexRouteImport
      parentRoute: typeof MatchesMatchIdRouteRoute
    }
    '/matches/$matchId/delete': {
      id: '/matches/$matchId/delete'
      path: '/delete'
      fullPath: '/matches/$matchId/delete'
      preLoaderRoute: typeof MatchesMatchIdDeleteRouteImport
      parentRoute: typeof MatchesMatchIdRouteRoute
    }
    '/warbands/$warbandId/': {
      id: '/warbands/$warbandId/'
      path: '/'
      fullPath: '/warbands/$warbandId/'
      preLoaderRoute: typeof WarbandsWarbandIdIndexRouteImport
      parentRoute: typeof WarbandsWarbandIdRouteRoute
    }
    '/warbands/$warbandId/delete': {
      id: '/warbands/$warbandId/delete'
      path: '/delete'
      fullPath: '/warbands/$warbandId/delete'
      preLoaderRoute: typeof WarbandsWarbandIdDeleteRouteImport
      parentRoute: typeof WarbandsWarbandIdRouteRoute
    }
    '/warriors/$warriorId/': {
      id: '/warriors/$warriorId/'
      path: '/'
      fullPath: '/warriors/$warriorId/'
      preLoaderRoute: typeof WarriorsWarriorIdIndexRouteImport
      parentRoute: typeof WarriorsWarriorIdRouteRoute
    }
    '/warriors/$warriorId/delete': {
      id: '/warriors/$warriorId/delete'
      path: '/delete'
      fullPath: '/warriors/$warriorId/delete'
      preLoaderRoute: typeof WarriorsWarriorIdDeleteRouteImport
      parentRoute: typeof WarriorsWarriorIdRouteRoute
    }
  }
}

interface EventsEventIdRouteRouteChildren {
  EventsEventIdDeleteRoute: typeof EventsEventIdDeleteRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
}

const EventsEventIdRouteRouteChildren: EventsEventIdRouteRouteChildren = {
  EventsEventIdDeleteRoute: EventsEventIdDeleteRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
}

const EventsEventIdRouteRouteWithChildren =
  EventsEventIdRouteRoute._addFileChildren(EventsEventIdRouteRouteChildren)

interface EventsRouteRouteChildren {
  EventsEventIdRouteRoute: typeof EventsEventIdRouteRouteWithChildren
  EventsIndexRoute: typeof EventsIndexRoute
}

const EventsRouteRouteChildren: EventsRouteRouteChildren = {
  EventsEventIdRouteRoute: EventsEventIdRouteRouteWithChildren,
  EventsIndexRoute: EventsIndexRoute,
}

const EventsRouteRouteWithChildren = EventsRouteRoute._addFileChildren(
  EventsRouteRouteChildren,
)

interface MatchesMatchIdRouteRouteChildren {
  MatchesMatchIdDeleteRoute: typeof MatchesMatchIdDeleteRoute
  MatchesMatchIdIndexRoute: typeof MatchesMatchIdIndexRoute
}

const MatchesMatchIdRouteRouteChildren: MatchesMatchIdRouteRouteChildren = {
  MatchesMatchIdDeleteRoute: MatchesMatchIdDeleteRoute,
  MatchesMatchIdIndexRoute: MatchesMatchIdIndexRoute,
}

const MatchesMatchIdRouteRouteWithChildren =
  MatchesMatchIdRouteRoute._addFileChildren(MatchesMatchIdRouteRouteChildren)

interface MatchesRouteRouteChildren {
  MatchesMatchIdRouteRoute: typeof MatchesMatchIdRouteRouteWithChildren
  MatchesIndexRoute: typeof MatchesIndexRoute
}

const MatchesRouteRouteChildren: MatchesRouteRouteChildren = {
  MatchesMatchIdRouteRoute: MatchesMatchIdRouteRouteWithChildren,
  MatchesIndexRoute: MatchesIndexRoute,
}

const MatchesRouteRouteWithChildren = MatchesRouteRoute._addFileChildren(
  MatchesRouteRouteChildren,
)

interface WarbandsWarbandIdRouteRouteChildren {
  WarbandsWarbandIdDeleteRoute: typeof WarbandsWarbandIdDeleteRoute
  WarbandsWarbandIdIndexRoute: typeof WarbandsWarbandIdIndexRoute
}

const WarbandsWarbandIdRouteRouteChildren: WarbandsWarbandIdRouteRouteChildren =
  {
    WarbandsWarbandIdDeleteRoute: WarbandsWarbandIdDeleteRoute,
    WarbandsWarbandIdIndexRoute: WarbandsWarbandIdIndexRoute,
  }

const WarbandsWarbandIdRouteRouteWithChildren =
  WarbandsWarbandIdRouteRoute._addFileChildren(
    WarbandsWarbandIdRouteRouteChildren,
  )

interface WarbandsRouteRouteChildren {
  WarbandsWarbandIdRouteRoute: typeof WarbandsWarbandIdRouteRouteWithChildren
  WarbandsIndexRoute: typeof WarbandsIndexRoute
}

const WarbandsRouteRouteChildren: WarbandsRouteRouteChildren = {
  WarbandsWarbandIdRouteRoute: WarbandsWarbandIdRouteRouteWithChildren,
  WarbandsIndexRoute: WarbandsIndexRoute,
}

const WarbandsRouteRouteWithChildren = WarbandsRouteRoute._addFileChildren(
  WarbandsRouteRouteChildren,
)

interface WarriorsWarriorIdRouteRouteChildren {
  WarriorsWarriorIdDeleteRoute: typeof WarriorsWarriorIdDeleteRoute
  WarriorsWarriorIdIndexRoute: typeof WarriorsWarriorIdIndexRoute
}

const WarriorsWarriorIdRouteRouteChildren: WarriorsWarriorIdRouteRouteChildren =
  {
    WarriorsWarriorIdDeleteRoute: WarriorsWarriorIdDeleteRoute,
    WarriorsWarriorIdIndexRoute: WarriorsWarriorIdIndexRoute,
  }

const WarriorsWarriorIdRouteRouteWithChildren =
  WarriorsWarriorIdRouteRoute._addFileChildren(
    WarriorsWarriorIdRouteRouteChildren,
  )

interface WarriorsRouteRouteChildren {
  WarriorsWarriorIdRouteRoute: typeof WarriorsWarriorIdRouteRouteWithChildren
  WarriorsIndexRoute: typeof WarriorsIndexRoute
}

const WarriorsRouteRouteChildren: WarriorsRouteRouteChildren = {
  WarriorsWarriorIdRouteRoute: WarriorsWarriorIdRouteRouteWithChildren,
  WarriorsIndexRoute: WarriorsIndexRoute,
}

const WarriorsRouteRouteWithChildren = WarriorsRouteRoute._addFileChildren(
  WarriorsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRouteRoute: EventsRouteRouteWithChildren,
  MatchesRouteRoute: MatchesRouteRouteWithChildren,
  WarbandsRouteRoute: WarbandsRouteRouteWithChildren,
  WarriorsRouteRoute: WarriorsRouteRouteWithChildren,
  DemoRoute: DemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
